jobs:
  CI:
    secrets: inherit
    strategy:
      matrix:
        include:
        - jdk: 8
          os: ubuntu-latest
          profile: ''
        - jdk: 8
          os: ubuntu-latest
          profile: -PtestNativeTransport
        - jdk: 8
          os: ubuntu-latest
          profile: -PtestDomainSockets
        - jdk: 21
          os: ubuntu-latest
          profile: ''
        - jdk: 8
          os: windows-latest
          profile: ''
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      profile: ${{ matrix.profile }}
  Deploy:
    if: ${{ github.repository_owner == 'eclipse-vertx' && (github.event_name == 'push'
      || github.event_name == 'schedule') }}
    needs: CI
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 4.x
      jdk: 8
name: vertx-core (4.x)
on:
  repository_dispatch:
    types: trigger-ga___ci-4.x.yml
